// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var IndexTsx = require("./components/index.tsx");

var make = IndexTsx.default;

var PokemonBattle = {
  make: make
};

function App(Props) {
  return React.createElement(make, {});
}

var make$1 = App;

exports.PokemonBattle = PokemonBattle;
exports.make = make$1;
/* make Not a pure module */
