// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDom = require("react-dom");
var App$ReactHooksTemplate = require("./App.bs.js");

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(App$ReactHooksTemplate.make, {}), root);
}

/* root Not a pure module */
